# Generated by Django 2.2.8 on 2020-09-04 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20200904_1014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_pix',
            field=models.URLField(verbose_name='Profile picture'),
        ),
    ]
