# Generated by Django 2.2.8 on 2020-09-05 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20200904_1204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='bio',
            field=models.CharField(blank=True, help_text='Professional Summary', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('Others', 'Others')], default='', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='languages',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='middle_name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Middle name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='nationality',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_pix',
            field=models.URLField(blank=True, null=True, verbose_name='avatar'),
        ),
        migrations.AlterField(
            model_name='user',
            name='resume',
            field=models.URLField(blank=True, null=True, verbose_name='resume'),
        ),
        migrations.AlterField(
            model_name='user',
            name='state_of_residence',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
