# Generated by Django 3.1.1 on 2021-01-06 08:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_auto_20210106_0945'),
    ]

    operations = [
        migrations.AlterField(
            model_name='template',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 6, 9, 55, 49, 953782)),
        ),
        migrations.AlterField(
            model_name='template',
            name='rating',
            field=models.CharField(choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=0, max_length=1),
        ),
    ]
