# Generated by Django 3.1.1 on 2021-01-06 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0024_auto_20210106_1000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='template',
            name='rating',
            field=models.CharField(choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=0, max_length=5),
        ),
    ]
