# Generated by Django 3.1.1 on 2021-01-06 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0025_auto_20210106_1002'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='template',
            name='rating',
        ),
    ]
