# Generated by Django 3.1.1 on 2021-01-10 20:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0031_auto_20210110_1950'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='template',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='template', to='accounts.template'),
            preserve_default=False,
        ),
    ]
