# Generated by Django 3.1.1 on 2021-01-11 12:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0032_auto_20210110_2006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='template',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='template', to='accounts.template'),
        ),
    ]
