# Generated by Django 3.1.1 on 2021-01-11 13:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0033_auto_20210111_1238'),
    ]

    operations = [
        migrations.AddField(
            model_name='template',
            name='filename',
            field=models.CharField(default='template', max_length=20, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='template',
            name='rating',
            field=models.PositiveIntegerField(default=0, max_length=5, validators=[django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='template',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
