# Generated by Django 3.1.1 on 2021-01-20 17:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0034_auto_20210111_1314'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='allow_download',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='template',
            name='rating',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(5)]),
        ),
    ]
