# Generated by Django 3.1.1 on 2021-01-28 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0036_auto_20210124_1651'),
    ]

    operations = [
        migrations.AddField(
            model_name='template',
            name='approved',
            field=models.BooleanField(default=False),
        ),
    ]
