# Generated by Django 3.1.1 on 2021-01-29 12:09

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0038_template_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='template',
            name='file',
            field=models.FileField(default='', upload_to='', validators=[accounts.models.validate_file_extension]),
        ),
    ]
