# Generated by Django 3.0.8 on 2020-07-15 18:16

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20200715_1912'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_pix',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='Profile picure'),
        ),
    ]
