# Generated by Django 3.0.8 on 2020-07-15 18:17

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20200715_1916'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectimage',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='Project Image'),
        ),
        migrations.AlterField(
            model_name='social',
            name='icon',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='Social icon'),
        ),
    ]
