# Generated by Django 2.2.8 on 2020-09-05 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='end_year',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='experience',
            name='end_year',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='experience',
            name='in_progress',
            field=models.BooleanField(default=True),
        ),
    ]
