# Generated by Django 3.1.1 on 2020-09-19 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0002_auto_20200905_1509'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='end_year',
            field=models.DateField(blank=True, null=True),
        ),
    ]
