# Generated by Django 3.1.1 on 2020-09-24 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0003_auto_20200919_2057'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='project_name',
        ),
        migrations.AddField(
            model_name='project',
            name='project_source',
            field=models.CharField(default='aa', help_text='Project source if provided url is link to other projects else name.', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sociallink',
            name='label',
            field=models.CharField(choices=[('Facebook', 'Facebook'), ('Twitter', 'Twitter'), ('Linkedin', 'Linkedin'), ('Website', 'Website'), ('Others', 'Others')], max_length=20, verbose_name='Social host i.e Facebook, twitter etc.'),
        ),
    ]
