# Generated by Django 3.1.1 on 2020-11-01 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0005_auto_20200928_1740'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sociallink',
            old_name='profile_url',
            new_name='social_url',
        ),
        migrations.RenameField(
            model_name='subskill',
            old_name='sub_skill',
            new_name='title',
        ),
        migrations.RemoveField(
            model_name='education',
            name='in_progress',
        ),
        migrations.AlterField(
            model_name='education',
            name='end_year',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_source',
            field=models.CharField(choices=[('Github', 'Github'), ('OTHER', 'Other')], default='', help_text='Project source if provided url is link to other projects else name.', max_length=50),
        ),
        migrations.AlterField(
            model_name='sociallink',
            name='label',
            field=models.CharField(max_length=20, verbose_name='Social host i.e Facebook, twitter etc.'),
        ),
    ]
