# Generated by Django 3.1.1 on 2020-11-03 13:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0006_auto_20201101_1827'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subskill',
            name='skill',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_skills', to='resume.skill'),
        ),
    ]
