# Generated by Django 3.1.1 on 2020-12-07 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0007_auto_20201103_1416'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='experience',
            name='in_progress',
        ),
        migrations.AlterField(
            model_name='education',
            name='end_year',
            field=models.CharField(max_length=9),
        ),
        migrations.AlterField(
            model_name='education',
            name='start_year',
            field=models.CharField(max_length=9),
        ),
        migrations.AlterField(
            model_name='experience',
            name='end_year',
            field=models.CharField(default=1, max_length=9),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='experience',
            name='start_year',
            field=models.CharField(max_length=9),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_source',
            field=models.CharField(default='', help_text='Project source if provided url is link to other projects else name.', max_length=50),
        ),
    ]
