# Generated by Django 3.1.1 on 2020-12-08 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0008_auto_20201207_1833'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='education',
            name='education_type',
        ),
        migrations.RemoveField(
            model_name='project',
            name='project_source',
        ),
    ]
