# Generated by Django 3.1.1 on 2020-12-09 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0009_auto_20201208_0840'),
    ]

    operations = [
        migrations.AddField(
            model_name='experience',
            name='position',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
