# Generated by Django 3.1.1 on 2020-12-14 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0011_auto_20201214_1317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sociallink',
            name='label',
            field=models.CharField(max_length=20, verbose_name='Social Host'),
        ),
    ]
