# Generated by Django 3.1.1 on 2020-12-15 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0012_auto_20201214_1705'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='course',
            field=models.CharField(default='', max_length=50, verbose_name='Discipline'),
        ),
        migrations.AlterField(
            model_name='education',
            name='degree',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='education',
            name='end_year',
            field=models.CharField(default='', max_length=9),
        ),
        migrations.AlterField(
            model_name='education',
            name='institution',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='education',
            name='start_year',
            field=models.CharField(default='', max_length=9),
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='title',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
    ]
