# Generated by Django 3.1.1 on 2021-01-06 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0015_accomplishment_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='education',
            name='in_progress',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='experience',
            name='in_progress',
            field=models.BooleanField(default=False),
        ),
    ]
